### ISSUE TITLE
Rückfrage Geschenkeliste

### ISSUE THREAD

**Issue by rencarol** [lightszentip/giftlist#143]
Hallo Tobi,

ich bin über die Geschenkeliste gestolpert und wollte diese installieren. Leider scheine ich irgendwie nicht in der Lage zu sein das Projekt bei mir zu starten. Ich habe eine neue Ubuntu-VM mit PHP 8.1, apache2 und mysql aufgesetzt. Beim Aufruf des public Verzeichnisses habe ich nur eine Seite mit "500
SERVER ERROR".
Hast Du vielleicht einen Tipp für mich?

Gruß René (rene@carolus.org)

**Comment by lightszentip** [comment]
Hallo Rene,

hast du die folgende Installationsanleitung ausgeführt:

```
Installation over Release Zip

    Download https://github.com/lightszentip/giftlist/releases/tag/1.0.4 giftlist-main.zip
    unzip in your nginx/apache folder
    set www root to public/
        nginx: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-laravel-with-nginx-on-ubuntu-20-04#step-5-setting-up-nginx
        apache: https://www.hostinger.com/tutorials/how-to-install-laravel-on-ubuntu-18-04-with-apache-and-php/#Using_Laravel_to_Deploy_an_Application
    create .env file in the root dir and set the settings

php artisan key:generate
php artisan migrate
php artisan db:seed
```


Folgende zwei Möglichkeiten gibt es damit du die Fehlermeldung bekommst, welche hinter dem 500 steht - sofern dein Webserver richtig konfiguriert ist:
a.) In der index.php den PHP Error setzen: https://www.php.net/manual/en/function.error-reporting.php
b.) In Laravel in der .env Datei den Wert APP_DEBUG=true auf true setzen

Gruß
Tobi

**Comment by rencarol** [comment]
Hi Tobi,
vielen Dank für die Rückmeldung. Ich habe die Anleitung etwas falsch verstanden, aber nun alle Schritte durchgeführt. 
Aktuell sehe ich schon was im Frontend, es wird der Wizard allerdings nicht aufgerufen. Ich bekomme eine Seite mit einem roten Label "Local Test" in der Ecke. 
Hast Du da auch noch einen Tipp?
Gruß
René
